### ISSUE TITLE
Prepare open-sourcing this repository

### ISSUE THREAD

**Issue by fmenou** [fretlink/ansible-clever#66]
### Some important steps before releasing it

- [x] Look for secrets in git history and revoke them if needed.
- [x] Documentation (notably examples?)
- [x] Some of the configuration and code here is haskell oriented, and this might be misleading to others
- [x] Have a working nodejs project using it before?
- [x] Make sure it's compatible with public travis-ci setup
- [x] Make it releasable to ansible-galaxy?
- [x] Remove Slack token from `.travis.yml` file (and from git history)

**Comment by paulrbr-fl** [comment]
The repo is now public :tada:
